{{- if .Values.ecommerce.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ecommerce.name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: ecommerce
spec:
  type: {{ .Values.ecommerce.service.type }}
  ports:
    - port: {{ .Values.ecommerce.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ecommerce
{{- end }}

